imdb_project/imdb_app/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views


app_name = 'imdb_app'

urlpatterns = [
    # User Paths
    path('signup/', views.SignUp.as_view(), name='signup'),

    # Movie Paths
    path(
        'movie/create',
        login_required(views.MovieCreateView.as_view()),
        name='movie_create'
    ),
    path(
        'movie/',
        login_required(views.MovieListView.as_view()),
        name='movie'
    ),
    path(
        'movie/<int:pk>',
        login_required(views.MovieDetailView.as_view()),
        name='movie_detail'
    ),
    path(
        'movie/<int:pk>/update',
        login_required(views.MovieEditView.as_view()),
        name='movie_edit'
    ),
    path(
        'movie/<int:pk>/delete',
        login_required(views.MovieDeleteView.as_view()),
        name='movie_delete'
    ),

    # Actor Paths
    path(
        'actor/create',
        login_required(views.ActorCreateView.as_view()),
        name='actor_create'
    ),
    path(
        'actor/',
        login_required(views.ActorListView.as_view()),
        name='actor'
    ),
    path(
        'actor/<int:pk>',
        login_required(views.ActorDetailView.as_view()),
        name='actor_detail'
    ),
    path(
        'actor/<int:pk>/update',
        login_required(views.ActorEditView.as_view()),
        name='actor_edit'
    ),
    path(
        'actor/<int:pk>/delete',
        login_required(views.ActorDeleteView.as_view()),
        name='actor_delete'
    ),

    # Award Paths
    path(
        'award/create',
        login_required(views.AwardCreateView.as_view()),
        name='award_create'
    ),
    path(
        'award/movie/list',
        login_required(views.AwardMovieListView.as_view()),
        name='award_movie_list'
    ),
    path(
        'award/actor/list',
        login_required(views.AwardActorListView.as_view()),
        name='award_actor_list'
    ),
    path(
        'award/',
        login_required(views.AwardListView.as_view()),
        name='award'
    ),
    path(
        'award/<int:pk>',
        login_required(views.AwardDetailView.as_view()),
        name='award_detail'
    ),
    path(
        'award/<int:pk>/update',
        login_required(views.AwardEditView.as_view()),
        name='award_edit'
    ),
    path(
        'award/<int:pk>/delete',
        login_required(views.AwardDeleteView.as_view()),
        name='award_delete'
    ),

    # Comment Paths
    path(
        'comment/<int:pk>/create',
        login_required(views.CommentCreateView.as_view()),
        name='comment_create'
    ),
    path(
        'comment/<int:pk>/update',
        login_required(views.CommentEditView.as_view()),
        name='comment_edit'
    ),
    path(
        'comment/<int:pk>/delete',
        login_required(views.CommentDeleteView.as_view()),
        name='comment_delete'
    ),
]

imdb_project/imdb_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('imdb_app.urls')),
    path(
        '',
        login_required(TemplateView.as_view(template_name='home.html')),
        name='home'
    )
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

imdb_project/imdb_app/forms.py
from django import forms
from .models import Movie, Actor, Award, User, Comment
from django.forms.fields import DateField
from django.contrib.auth.forms import UserCreationForm
import datetime


class SignUpForm(UserCreationForm):
    """ Get field for user registeration """
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField(
        max_length=254,
        help_text='Required. Inform a valid email address.'
    )

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
            'avatar'
        )


class PostMovieForm(forms.ModelForm):
    """ Create movie form excluding user in form """
    release_date = DateField(
        widget=forms.SelectDateWidget(
            years=range(datetime.date.today().year, 1800, -1))
        )

    class Meta:
        model = Movie
        exclude = ('author',)


class PostActorForm(forms.ModelForm):
    """ Create actor form excluding user in form """
    birthdate = DateField(
        widget=forms.SelectDateWidget(
            years=range(datetime.date.today().year, 1800, -1))
        )

    class Meta:
        model = Actor
        exclude = ('author',)


class PostAwardForm(forms.ModelForm):
    """ Create award form excluding user,
        content type and object id in form """
    date = DateField(
        widget=forms.SelectDateWidget(
            years=range(datetime.date.today().year, 1800, -1))
        )

    class Meta:
        model = Award
        exclude = ('author', 'content_type', 'object_id')


class PostCommentForm(forms.ModelForm):
    """ Create comment form """
    class Meta:
        model = Comment
        fields = ('comment_text',)

imdb_project/imdb_app/views.py
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.urls import reverse_lazy
from .models import Movie, Actor, Award, Comment
from .forms import (PostMovieForm,
                    PostActorForm,
                    PostAwardForm,
                    SignUpForm,
                    PostCommentForm)
from django.contrib.contenttypes.models import ContentType


"-------------------------Sign Up-------------------------------------"


class SignUp(generic.CreateView):
    """ Create New User, if success go back to login page """
    form_class = SignUpForm
    template_name = 'signup.html'
    success_url = reverse_lazy('login')


"-------------------------Movie-------------------------------------"


class MovieListView(generic.ListView):
    """ View list of movies """
    model = Movie
    # name to call in template
    context_object_name = 'movie_list'
    # template to show
    template_name = 'imdb_app/movie_page.html'
    # limit to 12 movies per page
    paginate_by = 12

    def get_context_data(self, **kwargs):
        """ Put form to kwargs to use in template """
        # get form to use in template
        kwargs['form'] = PostMovieForm()
        return super(MovieListView, self).get_context_data(**kwargs)


class MovieCreateView(generic.CreateView):
    """ Create movie and reverse back to movie page """
    # form to use to create
    form_class = PostMovieForm
    # if success reverse back to movie page
    success_url = reverse_lazy('imdb_app:movie')

    def form_valid(self, form):
        # get user that send the request
        form.instance.author = self.request.user
        return super(MovieCreateView, self).form_valid(form)


class MovieDetailView(generic.DetailView):
    """ Go to detail page of a specific movie with primary key """
    model = Movie

    def get_context_data(self, **kwargs):
        # get movie follow by it's primary key
        movie = Movie.objects.get(pk=self.kwargs['pk'])
        # get all of it's comments
        kwargs['comments'] = movie.comments.all()
        # get form to use in template
        kwargs['form'] = PostCommentForm()
        return super(MovieDetailView, self).get_context_data(**kwargs)


class MovieEditView(generic.UpdateView):
    """ Edit movie and reverse back to movie page """
    # form to use to edit
    form_class = PostMovieForm
    # get all movies objects
    queryset = Movie.objects.all()
    # template to use to show edit form
    template_name = 'imdb_app/edit.html'
    # if successfully edit reverse back to movie page
    success_url = reverse_lazy('imdb_app:movie')


class MovieDeleteView(generic.DeleteView):
    """ Delete movie by it's primary key and reverse back to movie page """
    # get all movies objects
    queryset = Movie.objects.all()
    # if delete success return to movie page
    success_url = reverse_lazy('imdb_app:movie')


"-------------------------Actor-------------------------------------"


class ActorListView(generic.ListView):
    """ View list of actors """
    model = Actor
    # name of model to use in template
    context_object_name = 'actor_list'
    # page to show all actors
    template_name = 'imdb_app/actor_page.html'
    # up to 12 actors per page
    paginate_by = 12

    def get_context_data(self, **kwargs):
        """ Put form to kwargs to use in template """
        kwargs['form'] = PostActorForm()
        return super(ActorListView, self).get_context_data(**kwargs)


class ActorCreateView(generic.CreateView):
    """ Create actor and reverse back to actor page """
    # form to use to create
    form_class = PostActorForm
    # if success reverse back to actor page
    success_url = reverse_lazy('imdb_app:actor')

    def form_valid(self, form):
        # get user that send the request and put it to form
        form.instance.author = self.request.user
        return super(ActorCreateView, self).form_valid(form)


class ActorDetailView(generic.DetailView):
    """ Go to detail page of a specific actor with primary key """
    model = Actor

    def get_context_data(self, **kwargs):
        # get actor follow by it's primary key
        actor = Actor.objects.get(pk=self.kwargs['pk'])
        # get all of it's comments
        kwargs['comments'] = actor.comments.all()
        # get form to use in template
        kwargs['form'] = PostCommentForm()
        return super(ActorDetailView, self).get_context_data(**kwargs)


class ActorEditView(generic.UpdateView):
    """ Edit actor and reverse back to actor page """
    # form to use to edit
    form_class = PostActorForm
    # get all actor objects
    queryset = Actor.objects.all()
    # template to use to show edit form
    template_name = 'imdb_app/edit.html'
    # if successfully edit reverse back to actor page
    success_url = reverse_lazy('imdb_app:actor')


class ActorDeleteView(generic.DeleteView):
    """ Delete actor by it's primary key and reverse back to actor page """
    # get all actor objects
    queryset = Actor.objects.all()
    # if delete success return to actor page
    success_url = reverse_lazy('imdb_app:actor')


"-------------------------Award-------------------------------------"


class AwardListView(generic.ListView):
    """ list all award data"""
    model = Award
    # name of model to use in template
    context_object_name = 'award_list'
    # temple to show awards
    template_name = 'imdb_app/award_page.html'

    def get_context_data(self, **kwargs):
        """ add varible to use data in template """
        # form to create award
        kwargs['form'] = PostAwardForm()
        # list of all movies
        kwargs['movie_list'] = Movie.objects.all()
        # list of all actors
        kwargs['actor_list'] = Actor.objects.all()
        # list all awarded movie
        kwargs['movie_award_list'] = Award.objects.filter(kind='Movie')
        # list all awarded actors
        kwargs['actor_award_list'] = Award.objects.filter(kind='Actor')
        return super(AwardListView, self).get_context_data(**kwargs)


class AwardMovieListView(generic.ListView):
    """ List all awarded movies view """
    model = Award
    # template to show
    template_name = 'imdb_app/award_list.html'

    def get_context_data(self, **kwargs):
        """ add variable to use data in template """
        # title of page
        kwargs['title'] = 'Movie Award'
        # form to create new award
        kwargs['form'] = PostAwardForm()
        # list of all awarded movies
        kwargs['data'] = Award.objects.filter(kind='Movie')
        return super(AwardMovieListView, self).get_context_data(**kwargs)


class AwardActorListView(generic.ListView):
    """ List all awarded actors view """
    model = Award
    # template to show
    template_name = 'imdb_app/award_list.html'

    def get_context_data(self, **kwargs):
        """ add variable to use data in template """
        # title of page
        kwargs['title'] = 'Actor Award'
        # form to create new award
        kwargs['form'] = PostAwardForm()
        # list of all awarded actors
        kwargs['data'] = Award.objects.filter(kind='Actor')
        return super(AwardActorListView, self).get_context_data(**kwargs)


class AwardCreateView(generic.CreateView):
    """ create new award view """
    form_class = PostAwardForm
    # if success redirect to award page
    success_url = reverse_lazy('imdb_app:award')

    def form_valid(self, form):
        """ get data for form """
        # get author
        form.instance.author = self.request.user
        # get object id
        form.instance.object_id = self.request._post['selected']
        # set variable to store kinh model
        model = self.request._post['kind'].lower()
        # get content type id (refference for model) for form
        form.instance.content_type_id = ContentType.objects.get(model=model).id
        return super(AwardCreateView, self).form_valid(form)


class AwardDetailView(generic.DetailView):
    """ show an award detail view"""
    model = Award

    def get_context_data(self, **kwargs):
        """ get variable to use in template """
        # get award by primary key
        award = Award.objects.get(pk=self.kwargs['pk'])
        # get all award comments
        kwargs['comments'] = award.comments.all()
        # form to create new comment
        kwargs['form'] = PostCommentForm()
        return super(AwardDetailView, self).get_context_data(**kwargs)


class AwardEditView(generic.UpdateView):
    """ edit award view """
    # form to use
    form_class = PostAwardForm
    # get all award objects
    queryset = Award.objects.all()
    # template for show
    template_name = 'imdb_app/award_edit.html'
    # if edit success redirect to award page
    success_url = reverse_lazy('imdb_app:award')

    def form_valid(self, form):
        """ fill form """
        # get author
        form.instance.author = self.request.user
        # get object id
        form.instance.object_id = self.request._post['selected']
        # set variable to store kinh model
        model = self.request._post['kind'].lower()
        # get content type id (refference for model) for form
        form.instance.content_type_id = ContentType.objects.get(model=model).id
        return super(AwardEditView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        """ get variable to use in template """
        # get all movie object
        kwargs['movie_list'] = Movie.objects.all()
        # get all actor object
        kwargs['actor_list'] = Actor.objects.all()
        return super(AwardEditView, self).get_context_data(**kwargs)


class AwardDeleteView(generic.DeleteView):
    """ delete award view """
    # get all award object
    queryset = Award.objects.all()
    # if delete success redirect to award page
    success_url = reverse_lazy('imdb_app:award')


"-------------------------Comment-------------------------------------"

imdb_project/templates/imdb_app/actor_page.html
{% extends 'base.html' %}

{% block title %}Actor{% endblock %}

{% block content %}

<h1 title="head-title">
  <b>Actor</b>
  <span id="add-button">
    <button type="button" class="btn btn-dark btn-outline-danger" data-toggle="modal" data-target="#Createmodal">Create</button>
  </span>
</h1><hr>
  <div class="container">
    <div class="row">
    {% for actor in actor_list %}
    <div class="col-sm">
    <div class="item item{{forloop.counter}}">

        <div class="object">
          <img class="object-image" src="{{ actor.image.url }}" onerror="this.src='/static/anonymous.jpg'">
          <div class="button-set">
            {% if user.is_superuser or user.is_staff or user.username == actor.author.username and user.is_authenticated %}
              <a href={% url 'imdb_app:actor_edit' actor.id %} class="edit-btn btn btn-dark btn-outline-danger">Edit</a>
              <button type="button" class="delete-btn btn btn-dark btn-outline-danger" data-toggle="modal" data-target="#Deletemodal{{forloop.counter}}">Delete</button>
            {% endif %}
            <a class="title-link" href={% url 'imdb_app:actor_detail' actor.id %}>
              <span class="title">
                {% if actor.get_name|length > 25 %}
                {{ actor.get_name|truncatechars:25 }}
                {% else %}
                {{ actor.get_name }}
                {% endif %}
              </span>
            </a>
          </div>

        </div>


      </div>
    </div>

      <form method="post" action='{% url "imdb_app:actor_delete" actor.id %}'>
        {% csrf_token %}
        <div id=Deletemodal{{forloop.counter}} class="modal fade" role="dialog">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Delete actor</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>
              <div class="modal-body">
                <p>Are you sure you want to delete "{{ actor }}"?</p>
              </div>
              <div class="modal-footer">
                <button type="submit" class="btn btn-dark btn-outline-danger">Yes</button>
                <button type="button" class="btn btn-dark btn-outline-danger" data-dismiss="modal">No</button>
              </div>
            </div>
          </div>
        </div>
      </form>

  {% empty %}
    No actors yet.
  {% endfor %}
</div>
</div>
</tbody>
</table>

<form method="post" action='{% url "imdb_app:actor_create"%}' enctype="multipart/form-data">
  {% csrf_token %}
  <div id=Createmodal class="modal fade" role="dialog">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Create actor</h5>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
          {% for field in form %}
              <div class="control-group">
                  <strong>{{ field.label_tag }}</strong>
                  <div class="controls">
                    {{ field }}
                    <span class="error-input">
                      {{ field.errors }}
                    </span>
                  </div>
              </div>
          {% endfor %}
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-dark btn-outline-danger">Submit</button>
        </div>
      </div>
    </div>
  </div>
</form>
<hr>
<div class="page-navigator">
  {% if page_obj.has_other_pages %}
    {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.paginator.page_range.0 }}"> << </a>
      <a href="?page={{ page_obj.previous_page_number }}"> <  </a>
    {% endif %}
    {{ page_obj.number }}
    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}"> > </a>
      <a href="?page={{ page_obj.paginator.num_pages }}"> >> </a>
    {% endif %}
  {% endif %}
</div>
{% endblock %}

imdb_project/templates/imdb_app/award_edit.html
{% extends 'base.html' %}

{% block title %}{{ award }}{% endblock %}

{% block content %}
<form class="award-edit-form" method="post">
  {% csrf_token %}
    {{ form.as_p }}
    <label for="id_selected" id="label_id_selected"></label>
    <select id='id_selected' name='selected' required></select>
    <script type="text/javascript">
      document.addEventListener("DOMContentLoaded", function() {
        showData();
      });
    </script>
    <button type="submit" class="btn btn-dark btn-outline-danger">Submit</button>
</form>

<script type="text/javascript">
  var movieList = [{% for movie in movie_list %}["{{ movie.id }}", "{{ movie }}"], {% endfor %}]
  var actorList = [{% for actor in actor_list %}["{{ actor.id }}", "{{ actor }}"], {% endfor %}]
</script>
{% endblock %}

imdb_project/templates/imdb_app/award_page.html
{% extends 'base.html' %}

{% block title %}Movie{% endblock %}\

{% block content %}
<!-- Page Content -->
<div class="container">

  <!-- Page Heading -->
  <h1 class="my-4">
    <b>Movie Award</b>
    <span id="add-button">
      <button type="button" class="btn btn-dark btn-outline-danger" data-toggle="modal" data-target="#Createmodal">Create</button>
    </span>
  </h1>
  <div class="row" style="position:relative">
    {% for award in movie_award_list|slice:":4" %}
      {% if award.kind == "Movie"%}
        <div class="col-lg-6 mb-4">
          <div class="card bg-dark">
            <img class="card-img" src="https://www.everywoman.com/sites/default/files/decorative-star-with-lamps-on-a-background-of-wall-modern-grungy-picture-id873928690.jpg" alt="Card image">
            <div class="card-img-overlay">
              <h1 class="card-title text-white">{{award.title}}</h1>
              <a href={% url 'imdb_app:award_detail' award.id %} class="btn btn-dark btn-outline-danger">view</a>
              {% if user.is_superuser or user.is_staff or user.username == actor.author.username and user.is_authenticated %}
                <a href={% url 'imdb_app:award_edit' award.id %} class="btn btn-dark btn-outline-danger">edit</a>
                <button type="button" class="btn btn-dark btn-outline-danger" data-toggle="modal" data-target="#Deletemodal{{forloop.counter}}">Delete</button>
              {% endif %}
              <form method="post" action="{% url 'imdb_app:award_delete' award.id %}">
                {% csrf_token %}
                <div id="Deletemodal{{forloop.counter}}" class="modal fade" role="dialog">
                  <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title">Delete Award</h5>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                      </div>
                      <div class="modal-body">
                        <p>Are you sure you want to delete "{{ award }}"?</p>
                      </div>
                      <div class="modal-footer">
                        <button type="submit" class="btn btn-dark btn-outline-danger">Yes</button>
                        <button type="button" class="btn btn-dark btn-outline-danger" data-dismiss="modal">No</button>
                      </div>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      {% endif %}
      {% empty %}
        No award yet
    {% endfor %}
    {% if movie_award_list|length > 4%}
      <a href={% url 'imdb_app:award_movie_list'%}  style="position:absolute; bottom:0px; right:0px;">Read more...</a>
    {% endif %}
  </div>
  <hr>

  <h1 class="my-4">
    <b>Actor Award</b>
  </h1>
  <div class="row" style="position:relative">
    {% for award in actor_award_list|slice:":4" %}
      {% if award.kind == "Actor"%}
        <div class="col-lg-6 mb-4">
          <div class="card bg-dark">
            <img class="card-img" src="https://www.everywoman.com/sites/default/files/decorative-star-with-lamps-on-a-background-of-wall-modern-grungy-picture-id873928690.jpg" alt="Card image">
            <div class="card-img-overlay">
              <h1 class="card-title text-white">{{award.title}}</h1>
              <a href={% url 'imdb_app:award_detail' award.id %} class="btn btn-dark btn-outline-danger">view</a>
              {% if user.is_superuser or user.is_staff or user.username == actor.author.username and user.is_authenticated %}
                <a href={% url 'imdb_app:award_edit' award.id %} class="btn btn-dark btn-outline-danger">edit</a>
                <button type="button" class="btn btn-dark btn-outline-danger" data-toggle="modal" data-target="#Deletemodal{{forloop.counter}}">Delete</button>
              {% endif %}
              <form method="post" action="{% url 'imdb_app:award_delete' award.id %}">
                {% csrf_token %}
                <div id=Deletemodal{{forloop.counter}} class="modal fade" role="dialog">
                  <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title">Delete Award</h5>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                      </div>
                      <div class="modal-body">
                        <p>Are you sure you want to delete "{{ award }}"?</p>
                      </div>
                      <div class="modal-footer">
                        <button type="submit" class="btn btn-dark btn-outline-danger">Yes</button>
                        <button type="button" class="btn btn-dark btn-outline-danger" data-dismiss="modal">No</button>
                      </div>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
        {% if actor_award_list|length > 4%}
          <a href={% url 'imdb_app:award_actor_list'%} style="position:absolute; bottom:0px; right:0px;">Read more...</a>
        {% endif %}
      {% endif %}
    {% endfor %}
  </div>
</div>


<form class="award-create-form" action="{% url 'imdb_app:award_create' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div id=Createmodal class="modal fade" role="dialog">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Create Award</h5>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
          {% for field in form %}
              <div class="control-group">
                  <strong>{{ field.label_tag }}</strong>
                  <div class="controls">
                    {{ field }}
                    <span class="error-input">
                      {{ field.errors }}
                    </span>
                  </div>
              </div>
          {% endfor %}
          <label for="id_selected" id="label_id_selected"></label>
          <select id='id_selected' name='selected' required></select>
          <script type="text/javascript">
            document.addEventListener("DOMContentLoaded", function() {
              showData();
            });
          </script>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-dark btn-outline-danger">Submit</button>
        </div>
      </div>
    </div>
  </div>
</form>

<script type="text/javascript">
  var movieList = [{% for movie in movie_list %}["{{ movie.id }}", "{{ movie }}"], {% endfor %}]
  var actorList = [{% for actor in actor_list %}["{{ actor.id }}", "{{ actor }}"], {% endfor %}]
</script>
{% endblock %}

imdb_project/templates/imdb_app/movie_page.html
{% extends 'base.html' %}

{% block title %}Movie{% endblock %}

{% block content %}

<h1 title="head-title">
  <b>Movie</b>
  <span id="add-button">
    <button type="button" class="btn btn-dark btn-outline-danger" data-toggle="modal" data-target="#Createmodal">Create</button>
  </span>
</h1><hr>
    <div class="container">
    <div class="row">
    {% for movie in movie_list %}
    <div class="col-sm">
      <div class="item item{{forloop.counter}}">
        <div class="object">
          <img class="object-image" src="{{ movie.image.url }}" onerror="this.src='/static/anonymous.jpg'" style="width:214px; height:317px">
          <div class="button-set">
            {% if user.is_superuser or user.is_staff or user.username == movie.author.username and user.is_authenticated %}
              <a href={% url 'imdb_app:movie_edit' movie.id %} class="edit-btn btn btn-dark btn-outline-danger">Edit</a>
              <button type="button" class="delete-btn btn btn-dark btn-outline-danger" data-toggle="modal" data-target="#Deletemodal{{forloop.counter}}">Delete</button>
            {% endif %}
            <a class="title-link" href={% url 'imdb_app:movie_detail' movie.id %}>
              <span class="title">
                {% if movie.title|length > 25 %}
                {{ movie.title|truncatechars:25 }}
                {% else %}
                {{ movie.title }}
                {% endif %}
                <br>
                ({{ movie.release_date|date:"Y" }})
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>

      <form method="post" action='{% url "imdb_app:movie_delete" movie.id %}'>
        {% csrf_token %}
        <div id=Deletemodal{{forloop.counter}} class="modal fade" role="dialog">
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Delete Movie</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>
              <div class="modal-body">
                <p>Are you sure you want to delete "{{ movie }}"?</p>
              </div>
              <div class="modal-footer">
                <button type="submit" class="btn btn-dark btn-outline-danger">Yes</button>
                <button type="button" class="btn btn-dark btn-outline-danger" data-dismiss="modal">No</button>
              </div>
            </div>
          </div>
        </div>
      </form>

  {% empty %}
    No movies yet.
  {% endfor %}
</div>
</div>
</tbody>
</table>

<form method="post" action='{% url "imdb_app:movie_create"%}' enctype="multipart/form-data">
  {% csrf_token %}
  <div id=Createmodal class="modal fade" role="dialog">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Create Movie</h5>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
          {% for field in form %}
              <div class="control-group">
                  <strong>{{ field.label_tag }}</strong>
                  <div class="controls">
                    {{ field }}
                    <span class="error-input">
                      {{ field.errors }}
                    </span>
                  </div>
              </div>
          {% endfor %}
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-dark btn-outline-danger">Submit</button>
        </div>
      </div>
    </div>
  </div>
</form>
<hr>
<div class="page-navigator">
  {% if page_obj.has_other_pages %}
    {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.paginator.page_range.0 }}"> << </a>
      <a href="?page={{ page_obj.previous_page_number }}"> <  </a>
    {% endif %}
    {{ page_obj.number }}
    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}"> > </a>
      <a href="?page={{ page_obj.paginator.num_pages }}"> >> </a>
    {% endif %}
  {% endif %}
</div>
{% endblock %}