imdb_project/imdb_app/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views


app_name = 'imdb_app'

urlpatterns = [
    # User Paths
    path('signup/', views.SignUp.as_view(), name='signup'),

    # Movie Paths
    path(
        'movie/create',
        login_required(views.MovieCreateView.as_view()),
        name='movie_create'
    ),
    path(
        'movie/',
        login_required(views.MovieListView.as_view()),
        name='movie'
    ),
    path(
        'movie/<int:pk>',
        login_required(views.MovieDetailView.as_view()),
        name='movie_detail'
    ),
    path(
        'movie/<int:pk>/update',
        login_required(views.MovieEditView.as_view()),
        name='movie_edit'
    ),
    path(
        'movie/<int:pk>/delete',
        login_required(views.MovieDeleteView.as_view()),
        name='movie_delete'
    ),

    # Actor Paths
    path(
        'actor/create',
        login_required(views.ActorCreateView.as_view()),
        name='actor_create'
    ),
    path(
        'actor/',
        login_required(views.ActorListView.as_view()),
        name='actor'
    ),
    path(
        'actor/<int:pk>',
        login_required(views.ActorDetailView.as_view()),
        name='actor_detail'
    ),
    path(
        'actor/<int:pk>/update',
        login_required(views.ActorEditView.as_view()),
        name='actor_edit'
    ),
    path(
        'actor/<int:pk>/delete',
        login_required(views.ActorDeleteView.as_view()),
        name='actor_delete'
    ),

    # Award Paths
    path(
        'award/create',
        login_required(views.AwardCreateView.as_view()),
        name='award_create'
    ),
    path(
        'award/movie/list',
        login_required(views.AwardMovieListView.as_view()),
        name='award_movie_list'
    ),
    path(
        'award/actor/list',
        login_required(views.AwardActorListView.as_view()),
        name='award_actor_list'
    ),
    path(
        'award/',
        login_required(views.AwardListView.as_view()),
        name='award'
    ),
    path(
        'award/<int:pk>',
        login_required(views.AwardDetailView.as_view()),
        name='award_detail'
    ),
    path(
        'award/<int:pk>/update',
        login_required(views.AwardEditView.as_view()),
        name='award_edit'
    ),
    path(
        'award/<int:pk>/delete',
        login_required(views.AwardDeleteView.as_view()),
        name='award_delete'
    ),

    # Comment Paths
    path(
        'comment/<int:pk>/create',
        login_required(views.CommentCreateView.as_view()),
        name='comment_create'
    ),
    path(
        'comment/<int:pk>/update',
        login_required(views.CommentEditView.as_view()),
        name='comment_edit'
    ),
    path(
        'comment/<int:pk>/delete',
        login_required(views.CommentDeleteView.as_view()),
        name='comment_delete'
    ),
]

imdb_project/imdb_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('imdb_app.urls')),
    path(
        '',
        login_required(TemplateView.as_view(template_name='home.html')),
        name='home'
    )
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

imdb_project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!--  Font  -->
    <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro" rel="stylesheet">

    <!--  CSS  -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!--  JavaScript -->
    <script type="text/javascript" src="{% static 'my_script.js' %}"></script>

  </head>

  <body background="{% static 'movies_background.jpg' %}">
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
      <div class="container">
        <a href="{% url 'home' %}" class="navbar-brand">
          <img id="logo" src="{% static 'intek_logo.png' %}" alt="logo"><b>INTEK IMDB</b>
        </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'imdb_app:movie' %}"><b>Movies</b></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'imdb_app:actor' %}"><b>Actors</b></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'imdb_app:award' %}"><b>Awards</b></a>
              </li>
            </ul>
            {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">
                  {% if not user.is_superuser %}
                    <img src="{{ user.avatar.url }}" width="45px" height="45px" style="border-radius: 50%;">
                    <b>Hello, {{ user.first_name }}</b>
                  {% else %}
                    <b>Hello, handsome</b>
                  {% endif %}
                </a>
                <div class="dropdown-menu navbar-light bg-dark">
                  <a class="dropdown-item bg-dark" href="#"><b>Edit Profile</b></a>
                  <a class="dropdown-item bg-dark" href="{% url 'logout' %}"><b>Logout</b></a>
              </div>
              </li>
            </ul>
            {% endif %}
          </div>
        </div>
      </nav>
        <div class="container page-background">
          {% block content %}
          {% endblock %}
        </div>
        {% block homepage %}
        {% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

imdb_project/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block homepage %}

<div class="home-page">
  <div class="home-page-title">
    <h1>WELCOME TO INTEK IMDB</h1>
    <h2>The best review website of your own!!</h2>
  </div>
</div>

{% endblock %}

imdb_project/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <fieldset>
    <div id="legend">
      <legend class="">Register</legend>
    </div>
    {% for field in form %}
        <div class="control-group">
            <strong>{{ field.label_tag }}</strong>
            <div class="controls">
              {{ field }}
              <span class="error-input">
                {{ field.errors }}
              </span>
            </div>
        </div>
    {% endfor %}
    <div class="control-group">
      <!-- Button -->
      <div class="controls">
        <button type="submit" class="btn btn-success">Register</button>
      </div>
    </div>
  </fieldset>
</form>
{% endblock %}